export type ProductSource = 'YouTube' | 'Google' | 'Comunidades';
export type ProductStatus = 'ALTA' | 'ESTÁVEL' | 'CAINDO';

export interface Product {
  id: string;
  name: string;
  price: string | number;
  image_url: string;
  hype_score: number;
  url: string;
  category?: string;
  status?: ProductStatus;
  commission?: string;
  vendas_mes?: number;
  description?: string;
  title?: string;
  score?: number;
  supplier?: string;
}

export const mockProducts: Product[] = [
  {
    "id": "1",
    "name": "Smartwatch W9 Pro Ultra Series 9 Tela Infinita AMOLED",
    "title": "Smartwatch W9 Pro Ultra Series 9 Tela Infinita AMOLED",
    "price": 149.9,
    "image_url": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&q=80&w=800",
    "hype_score": 99,
    "score": 99,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 47,90",
    "vendas_mes": 5420,
    "supplier": "TechMaster Brasil - SP",
    "description": "O smartwatch mais viral das redes com tela infinita, medição de saúde e bateria de longa duração."
  },
  {
    "id": "2",
    "name": "Fone Bluetooth TWS Gamer Lenovo GM2 Pro Baixa Latência",
    "title": "Fone Bluetooth TWS Gamer Lenovo GM2 Pro Baixa Latência",
    "price": 79.9,
    "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 25,50",
    "vendas_mes": 4310,
    "supplier": "Innova Tech - SP",
    "description": "Som estéreo espacial com isolamento acústico e iluminação futurista gamer."
  },
  {
    "id": "3",
    "name": "Câmera Lâmpada de Segurança 360 Wifi Espiã com Visão Noturna",
    "title": "Câmera Lâmpada de Segurança 360 Wifi Espiã com Visão Noturna",
    "price": 89.9,
    "image_url": "https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 29,90",
    "vendas_mes": 3890,
    "supplier": "Segurança Total - PR",
    "description": "Instalação simples no bocal da lâmpada, controle pelo celular e rastreamento de movimento."
  },
  {
    "id": "4",
    "name": "Mini Projetor Portátil 4K Cinema Pro 5G Wifi Integrado",
    "title": "Mini Projetor Portátil 4K Cinema Pro 5G Wifi Integrado",
    "price": 299,
    "image_url": "https://images.unsplash.com/photo-1535016120720-40c646bebbdc?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 95,00",
    "vendas_mes": 3120,
    "supplier": "Vision Pro - SP",
    "description": "Transforme qualquer parede em cinema com resolução 4K e sistema Android embutido."
  },
  {
    "id": "5",
    "name": "Carregador Power Bank 20.000mAh Turbo com Display Digital",
    "title": "Carregador Power Bank 20.000mAh Turbo com Display Digital",
    "price": 119.9,
    "image_url": "https://images.unsplash.com/photo-1609592426867-a0684f4ebfa4?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 38,00",
    "vendas_mes": 2890,
    "supplier": "Innova Tech - SP",
    "description": "Carregamento turbo ultra rápido para até 3 aparelhos simultâneos."
  },
  {
    "id": "6",
    "name": "Microfone de Lapela Sem Fio Duplo USB-C e Lightning",
    "title": "Microfone de Lapela Sem Fio Duplo USB-C e Lightning",
    "price": 89.9,
    "image_url": "https://loja.ctmd.eng.br/34608-large/microfone-condensador-profissional-cardioide-shure-138db.jpg",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 28,70",
    "vendas_mes": 2650,
    "supplier": "Creator Shop - RJ",
    "description": "O áudio profissional que os criadores de conteúdo do TikTok e Instagram utilizam."
  },
  {
    "id": "7",
    "name": "Caixa de Som Bluetooth À Prova Dágua T&G Bass Pro",
    "title": "Caixa de Som Bluetooth À Prova Dágua T&G Bass Pro",
    "price": 119.9,
    "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 38,30",
    "vendas_mes": 2450,
    "supplier": "AudioBrasil - SC",
    "description": "Graves potentes, certificação IPX6 contra água e autonomia de 12 horas."
  },
  {
    "id": "8",
    "name": "Rastreador Inteligente Anti-Perda compatível com Apple Find My",
    "title": "Rastreador Inteligente Anti-Perda compatível com Apple Find My",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=800",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 16,00",
    "vendas_mes": 2280,
    "supplier": "SmartTag BR - SP",
    "description": "Localize suas chaves, carteira, mala ou veículo direto pelo app sem mensalidade."
  },
  {
    "id": "9",
    "name": "Mini Seladora Térmica Portátil Recarregável a Vácuo",
    "title": "Mini Seladora Térmica Portátil Recarregável a Vácuo",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 16,00",
    "vendas_mes": 4890,
    "supplier": "CasaPrática - SP",
    "description": "Mantenha seus alimentos sempre frescos selando pacotes abertos em menos de 2 segundos."
  },
  {
    "id": "10",
    "name": "Cortador de Legumes Multifuncional 12 em 1 Mandoline Pro",
    "title": "Cortador de Legumes Multifuncional 12 em 1 Mandoline Pro",
    "price": 87.9,
    "image_url": "https://m.media-amazon.com/images/I/61Ec2TdhRWL._AC_UF1000,1000_QL80_.jpg",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 28,10",
    "vendas_mes": 4120,
    "supplier": "ChefPro Cozinha - MG",
    "description": "O cortador mais vendido do Brasil. Lâminas em aço inox para fatiar, ralar e cubos perfeitos."
  },
  {
    "id": "11",
    "name": "Batedor de Ovos e Bebidas Portátil Sem Fio Mixer Elétrico",
    "title": "Batedor de Ovos e Bebidas Portátil Sem Fio Mixer Elétrico",
    "price": 89.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1779631797/sipvxlzvr2llsrid2qmc.jpg",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 28,70",
    "vendas_mes": 3450,
    "supplier": "CasaPrática - SP",
    "description": "Batedor sem fio com motor silencioso para café cremoso, shakes e receitas rápidas."
  },
  {
    "id": "12",
    "name": "Triturador Elétrico de Alho e Alimentos USB 250ml",
    "title": "Triturador Elétrico de Alho e Alimentos USB 250ml",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 13,00",
    "vendas_mes": 3100,
    "supplier": "Praticidade Lar - SP",
    "description": "Pique alho, cebola e temperos com 1 toque sem deixar cheiro nas mãos."
  },
  {
    "id": "13",
    "name": "Dispenser Automático de Pasta de Dente com Esterilizador UV",
    "title": "Dispenser Automático de Pasta de Dente com Esterilizador UV",
    "price": 79.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1779676433/t9y5gf21oqbr2j0ipglf.jpg",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 25,50",
    "vendas_mes": 2780,
    "supplier": "EcoBanho - SP",
    "description": "Elimina bactérias das escovas por luz ultravioleta e dosa a pasta sem sujeira."
  },
  {
    "id": "14",
    "name": "Organizador de Canto em Bambu e Inox Multiuso",
    "title": "Organizador de Canto em Bambu e Inox Multiuso",
    "price": 189.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1779761533/m5fdmmwgaptszvqpd9r8.jpg",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 60,70",
    "vendas_mes": 2210,
    "supplier": "DecorBambu - RS",
    "description": "Design premium escandinavo para otimizar espaço em cozinhas e banheiros."
  },
  {
    "id": "15",
    "name": "Garrafa Pulverizadora Spray de Azeite e Óleo Culinário",
    "title": "Garrafa Pulverizadora Spray de Azeite e Óleo Culinário",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=800",
    "hype_score": 91,
    "score": 91,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 13,00",
    "vendas_mes": 2150,
    "supplier": "Airfryer Pro - SP",
    "description": "O acessório perfeito para Airfryer e saladas com névoa fina e zero desperdício."
  },
  {
    "id": "16",
    "name": "Mop Giratório Limpeza Prática 360 com Balde Lava e Seca",
    "title": "Mop Giratório Limpeza Prática 360 com Balde Lava e Seca",
    "price": 99.9,
    "image_url": "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&q=80&w=800",
    "hype_score": 90,
    "score": 90,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 32,00",
    "vendas_mes": 1980,
    "supplier": "LimpezaFácil - MG",
    "description": "Limpe o chão 3 vezes mais rápido sem molhar ou sujar as mãos."
  },
  {
    "id": "17",
    "name": "Escova Secadora e Alisadora Rotativa 3 em 1 Cerâmica Ionizada",
    "title": "Escova Secadora e Alisadora Rotativa 3 em 1 Cerâmica Ionizada",
    "price": 139.9,
    "image_url": "https://images.unsplash.com/photo-1522338242992-e1a54906a8da?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 44,70",
    "vendas_mes": 4620,
    "supplier": "BelezaReal - SP",
    "description": "Cabelos secos, lisos e modelados com brilho de salão em minutos."
  },
  {
    "id": "18",
    "name": "Massageador Facial Antirrugas Lifting Facial LED Photon",
    "title": "Massageador Facial Antirrugas Lifting Facial LED Photon",
    "price": 89.9,
    "image_url": "https://images.unsplash.com/photo-1512290900672-1f4864f77c08?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 29,90",
    "vendas_mes": 3540,
    "supplier": "SkinGlow - RJ",
    "description": "Tecnologia de microcorrente e luzes terapêuticas para estímulo de colágeno."
  },
  {
    "id": "19",
    "name": "Modelador de Cachos Automático Sem Fio Bateria USB",
    "title": "Modelador de Cachos Automático Sem Fio Bateria USB",
    "price": 149.9,
    "image_url": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 48,00",
    "vendas_mes": 2890,
    "supplier": "BelezaReal - SP",
    "description": "Ondas perfeitas e cachos automáticos sem risco de queimar os dedos."
  },
  {
    "id": "20",
    "name": "Kit Cílios Postiços Magnéticos com Delineador Líquido",
    "title": "Kit Cílios Postiços Magnéticos com Delineador Líquido",
    "price": 59.9,
    "image_url": "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 19,00",
    "vendas_mes": 2540,
    "supplier": "GlamourBR - SP",
    "description": "Aplicação magnética rápida sem necessidade de cola que danifica os cílios naturais."
  },
  {
    "id": "21",
    "name": "Aparelho Removedor de Cravos e Espinhas a Vácuo com Sucção",
    "title": "Aparelho Removedor de Cravos e Espinhas a Vácuo com Sucção",
    "price": 79.9,
    "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=800",
    "hype_score": 91,
    "score": 91,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 25,50",
    "vendas_mes": 2190,
    "supplier": "DermoClean - PR",
    "description": "Limpeza de pele profunda em casa com 5 níveis de sucção ajustáveis."
  },
  {
    "id": "22",
    "name": "Lâmpada de Monitor Barra LED RGB Screenbar com Sensor Touch",
    "title": "Lâmpada de Monitor Barra LED RGB Screenbar com Sensor Touch",
    "price": 89.9,
    "image_url": "https://images.unsplash.com/photo-1547082299-de196ea013d6?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 28,70",
    "vendas_mes": 4100,
    "supplier": "GamerZone - SP",
    "description": "Iluminação assimétrica que protege a visão eliminando reflexos na tela do monitor."
  },
  {
    "id": "23",
    "name": "Mousepad Gamer Extra Grande 90x40cm Mapa Múndi Emborrachado",
    "title": "Mousepad Gamer Extra Grande 90x40cm Mapa Múndi Emborrachado",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 16,00",
    "vendas_mes": 3340,
    "supplier": "GamerZone - SP",
    "description": "Superfície speed ultra lisa com bordas costuradas de alta durabilidade."
  },
  {
    "id": "24",
    "name": "Teclado Mecânico Compacto 60% RGB Switch Blue Hot-Swappable",
    "title": "Teclado Mecânico Compacto 60% RGB Switch Blue Hot-Swappable",
    "price": 169.9,
    "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 54,00",
    "vendas_mes": 2780,
    "supplier": "CyberDesk - SP",
    "description": "Design minimalista compacto com feedback tátil ultra responsivo."
  },
  {
    "id": "25",
    "name": "Suporte Articulado a Gás para Monitores com Ajuste 360",
    "title": "Suporte Articulado a Gás para Monitores com Ajuste 360",
    "price": 189.9,
    "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 60,00",
    "vendas_mes": 2320,
    "supplier": "ErgoDesign - SC",
    "description": "Postura perfeita e mesa 100% livre com pistão a gás suave e robusto."
  },
  {
    "id": "26",
    "name": "Garrafa Térmica Motivacional 2 Litros Degradê com Adesivos 3D",
    "title": "Garrafa Térmica Motivacional 2 Litros Degradê com Adesivos 3D",
    "price": 59.9,
    "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 19,00",
    "vendas_mes": 4950,
    "supplier": "FitLife Brasil - SP",
    "description": "A garrafa viral do TikTok que incentiva a hidratação diária com marcadores de horário."
  },
  {
    "id": "27",
    "name": "Kit 5 Faixas Elásticas Extensoras Mini Bands para Treino em Casa",
    "title": "Kit 5 Faixas Elásticas Extensoras Mini Bands para Treino em Casa",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 13,00",
    "vendas_mes": 3820,
    "supplier": "FitLife Brasil - SP",
    "description": "Cinco intensidades de resistência para glúteos, pernas e braços em qualquer lugar."
  },
  {
    "id": "28",
    "name": "Rolo Massageador Muscular Foam Roller Liberação Miofascial",
    "title": "Rolo Massageador Muscular Foam Roller Liberação Miofascial",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&q=80&w=800",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 22,00",
    "vendas_mes": 2190,
    "supplier": "SportPro - PR",
    "description": "Alívio imediato de dores musculares e tensão após treinos e rotina pesada."
  },
  {
    "id": "29",
    "name": "Tapete de Yoga e Pilates Antiderrapante EVA 10mm Extra Macio",
    "title": "Tapete de Yoga e Pilates Antiderrapante EVA 10mm Extra Macio",
    "price": 79.9,
    "image_url": "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&q=80&w=800",
    "hype_score": 90,
    "score": 90,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 25,50",
    "vendas_mes": 1890,
    "supplier": "ZenGym - SP",
    "description": "Amortecimento ideal para proteger joelhos e coluna durante exercícios no chão."
  },
  {
    "id": "30",
    "name": "Aspirador de Pó Sem Fio Automotivo e Doméstico Alta Sucção",
    "title": "Aspirador de Pó Sem Fio Automotivo e Doméstico Alta Sucção",
    "price": 99.9,
    "image_url": "https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 32,00",
    "vendas_mes": 4420,
    "supplier": "AutoTech Express - SP",
    "description": "Potência surpreendente de sucção para limpar bancos, painel, teclados e frestas."
  },
  {
    "id": "31",
    "name": "Suporte Celular Veicular Indução Automático MagSafe 15W",
    "title": "Suporte Celular Veicular Indução Automático MagSafe 15W",
    "price": 89.9,
    "image_url": "https://images.unsplash.com/photo-1586105251261-72a756497a11?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 29,90",
    "vendas_mes": 3670,
    "supplier": "AutoTech Express - SP",
    "description": "Trava magnética ultra firme que carrega seu aparelho por indução sem cabos soltos."
  },
  {
    "id": "32",
    "name": "Intercomunicador Bluetooth V2 para Capacete de Moto Prova Dágua",
    "title": "Intercomunicador Bluetooth V2 para Capacete de Moto Prova Dágua",
    "price": 289.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1779676505/jsfylaae9w4lcbftcewj.jpg",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 92,00",
    "vendas_mes": 2810,
    "supplier": "MotoClub - SP",
    "description": "Comunicação cristalina e atendimento de chamadas telefônicas em alta velocidade."
  },
  {
    "id": "33",
    "name": "Compressor de Ar Portátil Digital Calibrador de Pneus USB",
    "title": "Compressor de Ar Portátil Digital Calibrador de Pneus USB",
    "price": 169.9,
    "image_url": "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=800",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 54,00",
    "vendas_mes": 2150,
    "supplier": "AutoSegura - SP",
    "description": "Calibre pneus de carro, moto e bicicleta em segundos sem ir ao posto."
  },
  {
    "id": "34",
    "name": "Mochila Notebook Impermeável Executiva com Entrada USB",
    "title": "Mochila Notebook Impermeável Executiva com Entrada USB",
    "price": 119.9,
    "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 38,00",
    "vendas_mes": 3950,
    "supplier": "Bolsas & Cia - SP",
    "description": "Compartimento acolchoado para notebook, tecido repelente à água e porta USB externa."
  },
  {
    "id": "35",
    "name": "Bolsa Feminina Transversal Joey de Luxo Alça em Corrente",
    "title": "Bolsa Feminina Transversal Joey de Luxo Alça em Corrente",
    "price": 189.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1779628861/nwueymcgocc18bhfftl8.webp",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 60,70",
    "vendas_mes": 3210,
    "supplier": "CouroFino - RS",
    "description": "Acabamento matelassê elegante e ferragens douradas que valorizam qualquer produção."
  },
  {
    "id": "36",
    "name": "Calça Jogger Minimalista Soft Comfort Unissex",
    "title": "Calça Jogger Minimalista Soft Comfort Unissex",
    "price": 189.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1780241187/umwqblqntggmalzuby3u.jpg",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 60,70",
    "vendas_mes": 2650,
    "supplier": "StreetWear BR - SP",
    "description": "Modelagem moderna e toque super macio para máxima versatilidade no dia a dia."
  },
  {
    "id": "37",
    "name": "Sandália Crocs Feminina Soft Comfort com Pins",
    "title": "Sandália Crocs Feminina Soft Comfort com Pins",
    "price": 189.9,
    "image_url": "https://cdn.dooca.store/1290/products/crocband-white-pink-caramel-2_640x640+fill_ffffff.jpg?v=1755529361&webp=0",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 60,70",
    "vendas_mes": 2420,
    "supplier": "Calçados Brasil - SP",
    "description": "Leveza ortopédica e design moderno com solado antiderrapante."
  },
  {
    "id": "38",
    "name": "Lâmpada Lua Cheia 3D Touch 16 Cores RGB com Suporte de Madeira",
    "title": "Lâmpada Lua Cheia 3D Touch 16 Cores RGB com Suporte de Madeira",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1532767153582-b1a0e5145009?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 22,00",
    "vendas_mes": 3590,
    "supplier": "Luz & Arte - SP",
    "description": "Impressão 3D hiper-realista com controle remoto e sensor de toque sensível."
  },
  {
    "id": "39",
    "name": "Boneco Colecionável Sonny Angel Série Sweet Decoração",
    "title": "Boneco Colecionável Sonny Angel Série Sweet Decoração",
    "price": 127.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1780783993/k7mjdmcebbcxfjzepomd.webp",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 41,00",
    "vendas_mes": 3120,
    "supplier": "ToyCollector - SP",
    "description": "A febre mundial dos colecionáveis blind box para decorar quartos e mesas."
  },
  {
    "id": "40",
    "name": "Bandeira Oficial do Brasil Copa do Mundo 2026 150x105cm",
    "title": "Bandeira Oficial do Brasil Copa do Mundo 2026 150x105cm",
    "price": 39.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1780320783/bandeira_brasil_2026_yhdamv.jpg",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 13,00",
    "vendas_mes": 2890,
    "supplier": "Torcida Verde Amarela - SP",
    "description": "Tecido premium com cores vibrantes e costura dupla reforçada para a Copa."
  },
  {
    "id": "41",
    "name": "Suporte de Celular PopSocket Estético Studio Ghibli",
    "title": "Suporte de Celular PopSocket Estético Studio Ghibli",
    "price": 49.9,
    "image_url": "https://m.media-amazon.com/images/I/91QcppY+juL.jpg",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 16,00",
    "vendas_mes": 2450,
    "supplier": "GeekWorld - SP",
    "description": "Segurança ergonômica contra quedas com ilustrações colecionáveis adoradas."
  },
  {
    "id": "42",
    "name": "Aspirador de Pó Sem Fio Airbot Swift Alta Potência",
    "title": "Aspirador de Pó Sem Fio Airbot Swift Alta Potência",
    "price": 749.9,
    "image_url": "https://res.cloudinary.com/dwtefghdi/image/upload/v1780001839/qzonzlcs6eob01alv9to.webp",
    "hype_score": 91,
    "score": 91,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 240,00",
    "vendas_mes": 1820,
    "supplier": "HomeClean Lux - SP",
    "description": "Aspirador vertical ciclônico de última geração com filtro HEPA e motor brushless."
  },
  {
    "id": "43",
    "name": "Projetor Smart Magcubic Hy300 4K Android 11 Wi-Fi 6",
    "title": "Projetor Smart Magcubic Hy300 4K Android 11 Wi-Fi 6",
    "price": 289.9,
    "image_url": "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&q=80&w=800",
    "hype_score": 99,
    "score": 99,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 92,70",
    "vendas_mes": 6120,
    "supplier": "TechMaster Brasil - SP",
    "description": "O projetor mais vendido do TikTok Shop com rotação 180° e aplicativos nativos de streaming."
  },
  {
    "id": "44",
    "name": "Mini Impressora Térmica Portátil Sem Fio Bluetooth para Fotos e Etiquetas",
    "title": "Mini Impressora Térmica Portátil Sem Fio Bluetooth para Fotos e Etiquetas",
    "price": 119.9,
    "image_url": "https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 38,00",
    "vendas_mes": 5210,
    "supplier": "PrintPocket - SP",
    "description": "Imprima fotos, anotações e etiquetas direto do celular sem gastar uma gota de tinta."
  },
  {
    "id": "45",
    "name": "Ring Light LED 26cm com Tripé Profissional 2.10m e Suporte para Celular",
    "title": "Ring Light LED 26cm com Tripé Profissional 2.10m e Suporte para Celular",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 22,30",
    "vendas_mes": 4780,
    "supplier": "Creator Studio - RJ",
    "description": "Iluminação perfeita com 3 tons de cor e 10 níveis de brilho para lives e vídeos em alta definição."
  },
  {
    "id": "46",
    "name": "Cabo Magnético 3 em 1 Carga Rápida LED Giratório 540 Graus",
    "title": "Cabo Magnético 3 em 1 Carga Rápida LED Giratório 540 Graus",
    "price": 34.9,
    "image_url": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 11,10",
    "vendas_mes": 4320,
    "supplier": "Innova Tech - SP",
    "description": "Conector giratório magnético ultra resistente compatível com iPhone, Tipo-C e Micro-USB."
  },
  {
    "id": "47",
    "name": "Carregador por Indução 3 em 1 Sem Fio Dobrável Magsafe 15W",
    "title": "Carregador por Indução 3 em 1 Sem Fio Dobrável Magsafe 15W",
    "price": 129.9,
    "image_url": "https://images.unsplash.com/photo-1622445268045-8178a9c3954f?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 41,50",
    "vendas_mes": 3890,
    "supplier": "Innova Tech - SP",
    "description": "Carregue seu iPhone, Apple Watch e AirPods simultaneamente em uma estação compacta dobrável."
  },
  {
    "id": "48",
    "name": "Mini Drone Dobrável com Câmera Dual 4K HD e Sensor Anti-Colisão",
    "title": "Mini Drone Dobrável com Câmera Dual 4K HD e Sensor Anti-Colisão",
    "price": 249.9,
    "image_url": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 79,90",
    "vendas_mes": 3410,
    "supplier": "AeroTech - PR",
    "description": "Fácil de pilotar com estabilização por giroscópio e transmissão ao vivo no celular."
  },
  {
    "id": "49",
    "name": "Mini Caixa de Som Portátil Bluetooth Vintage Retrô Madeira",
    "title": "Mini Caixa de Som Portátil Bluetooth Vintage Retrô Madeira",
    "price": 89.9,
    "image_url": "https://images.unsplash.com/photo-1543512214-318c7553f230?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Eletrônicos",
    "commission": "R$ 28,70",
    "vendas_mes": 3120,
    "supplier": "VintageSound - SP",
    "description": "Estilo clássico nostálgico dos anos 50 com graves profundos e rádio FM integrado."
  },
  {
    "id": "50",
    "name": "Controle Gamepad Sem Fio Bluetooth para Celular, PC e TV Box",
    "title": "Controle Gamepad Sem Fio Bluetooth para Celular, PC e TV Box",
    "price": 109.9,
    "image_url": "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 35,00",
    "vendas_mes": 2950,
    "supplier": "GamerZone - SP",
    "description": "Pegada ergonômica com gatilhos de alta precisão e suporte retrátil para smartphone."
  },
  {
    "id": "51",
    "name": "Copo Térmico Quencher Tumbler 1.2L com Canudo e Alça Ergonômica",
    "title": "Copo Térmico Quencher Tumbler 1.2L com Canudo e Alça Ergonômica",
    "price": 79.9,
    "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=800",
    "hype_score": 99,
    "score": 99,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 25,50",
    "vendas_mes": 6850,
    "supplier": "ChefPro Cozinha - MG",
    "description": "A maior febre das redes sociais! Mantém bebidas geladas por até 24 horas sem suar por fora."
  },
  {
    "id": "52",
    "name": "Forma de Silicone Antiaderente Reutilizável para Fritadeira Air Fryer",
    "title": "Forma de Silicone Antiaderente Reutilizável para Fritadeira Air Fryer",
    "price": 34.9,
    "image_url": "https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 11,10",
    "vendas_mes": 5980,
    "supplier": "Airfryer Pro - SP",
    "description": "Acabe com a sujeira e a gordura no cesto da Airfryer com silicone premium lavável."
  },
  {
    "id": "53",
    "name": "Afiador Amolador de Facas Profissional 4 em 1 com Base Antiderrapante",
    "title": "Afiador Amolador de Facas Profissional 4 em 1 com Base Antiderrapante",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 12,70",
    "vendas_mes": 4420,
    "supplier": "ChefPro Cozinha - MG",
    "description": "Restaure o fio navalha de suas facas de cozinha e tesouras em menos de 10 segundos."
  },
  {
    "id": "54",
    "name": "Balança Digital de Cozinha Alta Precisão 10kg com Display LCD",
    "title": "Balança Digital de Cozinha Alta Precisão 10kg com Display LCD",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 12,70",
    "vendas_mes": 4120,
    "supplier": "CasaPrática - SP",
    "description": "Indispensável para dietas, receitas precisas e controle calórico diário."
  },
  {
    "id": "55",
    "name": "Bomba Elétrica Recarregável para Galão de Água Touch USB",
    "title": "Bomba Elétrica Recarregável para Galão de Água Touch USB",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Cozinha",
    "commission": "R$ 12,70",
    "vendas_mes": 3750,
    "supplier": "Praticidade Lar - SP",
    "description": "Dispense a água do galão com apenas 1 clique sem esforço de virar pesos pesados."
  },
  {
    "id": "56",
    "name": "Kit Potes Herméticos de Vidro com Tampa de Bambu 4 Peças",
    "title": "Kit Potes Herméticos de Vidro com Tampa de Bambu 4 Peças",
    "price": 119.9,
    "image_url": "https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 38,30",
    "vendas_mes": 2980,
    "supplier": "DecorBambu - RS",
    "description": "Organização estética Pinterest para despensas e armários modernos com vedação de silicone."
  },
  {
    "id": "57",
    "name": "Umidificador e Difusor de Aromas Ultrassônico Efeito Chama LED",
    "title": "Umidificador e Difusor de Aromas Ultrassônico Efeito Chama LED",
    "price": 99.9,
    "image_url": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 32,00",
    "vendas_mes": 4890,
    "supplier": "Luz & Arte - SP",
    "description": "Névoa aromática com iluminação LED que simula uma lareira aconchegante e relaxante."
  },
  {
    "id": "58",
    "name": "Luminária Noturna com Sensor de Presença LED Magnética Recarregável",
    "title": "Luminária Noturna com Sensor de Presença LED Magnética Recarregável",
    "price": 44.9,
    "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Casa & Decoração",
    "commission": "R$ 14,30",
    "vendas_mes": 3620,
    "supplier": "Luz & Arte - SP",
    "description": "Acende automaticamente ao detectar movimento no escuro. Fixação magnética sem fios."
  },
  {
    "id": "59",
    "name": "Depilador de Cristal Corporal Indolor Nanotecnologia Esfoliante",
    "title": "Depilador de Cristal Corporal Indolor Nanotecnologia Esfoliante",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 12,70",
    "vendas_mes": 5420,
    "supplier": "BelezaReal - SP",
    "description": "Depilação suave sem lâminas ou dor, removendo pelos e células mortas simultaneamente."
  },
  {
    "id": "60",
    "name": "Kit 12 Pincéis de Maquiagem Profissional com Estojo de Couro",
    "title": "Kit 12 Pincéis de Maquiagem Profissional com Estojo de Couro",
    "price": 59.9,
    "image_url": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 19,00",
    "vendas_mes": 3890,
    "supplier": "GlamourBR - SP",
    "description": "Cerdas sintéticas macias de alta densidade que não absorvem excesso de maquiagem."
  },
  {
    "id": "61",
    "name": "Rolo Facial de Jade Roller e Pedra Gua Sha Natural Massagem",
    "title": "Rolo Facial de Jade Roller e Pedra Gua Sha Natural Massagem",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 16,00",
    "vendas_mes": 3410,
    "supplier": "SkinGlow - RJ",
    "description": "Drenagem linfática facial natural para desinchar o rosto e amenizar linhas finas."
  },
  {
    "id": "62",
    "name": "Caneta Depiladora Aparadora de Sobrancelha Elétrica Indolor LED",
    "title": "Caneta Depiladora Aparadora de Sobrancelha Elétrica Indolor LED",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 12,70",
    "vendas_mes": 2950,
    "supplier": "GlamourBR - SP",
    "description": "Design em formato de batom com ponta de precisão banhada a ouro 18k e luz LED integrada."
  },
  {
    "id": "63",
    "name": "Sérum Facial Clareador Vitamina C 10% com Ácido Hialurônico 30ml",
    "title": "Sérum Facial Clareador Vitamina C 10% com Ácido Hialurônico 30ml",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 22,30",
    "vendas_mes": 4180,
    "supplier": "DermoClean - PR",
    "description": "Ação antioxidante potente que uniformiza o tom da pele e hidrata profundamente."
  },
  {
    "id": "64",
    "name": "Máscara de Dormir 3D Bloqueio Total de Luz com Alça Ajustável",
    "title": "Máscara de Dormir 3D Bloqueio Total de Luz com Alça Ajustável",
    "price": 34.9,
    "image_url": "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&q=80&w=800",
    "hype_score": 91,
    "score": 91,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Beleza",
    "commission": "R$ 11,10",
    "vendas_mes": 2650,
    "supplier": "ZenSleep - SP",
    "description": "Espuma com cavidade para os olhos sem pressionar pálpebras, garantindo escuridão absoluta."
  },
  {
    "id": "65",
    "name": "Suporte Articulado Dobrável em Alumínio Ergonômico para Notebook",
    "title": "Suporte Articulado Dobrável em Alumínio Ergonômico para Notebook",
    "price": 79.9,
    "image_url": "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 25,50",
    "vendas_mes": 4890,
    "supplier": "ErgoDesign - SC",
    "description": "Regulagem em 6 níveis de altura para evitar dores no pescoço e melhorar ventilação."
  },
  {
    "id": "66",
    "name": "Hub Adaptador USB-C 7 em 1 HDMI 4K USB 3.0 Cartão SD PD 100W",
    "title": "Hub Adaptador USB-C 7 em 1 HDMI 4K USB 3.0 Cartão SD PD 100W",
    "price": 129.9,
    "image_url": "https://images.unsplash.com/photo-1544652478-6653e09f18a2?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 41,50",
    "vendas_mes": 3950,
    "supplier": "Innova Tech - SP",
    "description": "Conecte monitor secundário, pendrive, teclado e carregador com velocidade máxima."
  },
  {
    "id": "67",
    "name": "Fita de LED RGB 5050 5 Metros com Controle Remoto e Bluetooth",
    "title": "Fita de LED RGB 5050 5 Metros com Controle Remoto e Bluetooth",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 16,00",
    "vendas_mes": 4320,
    "supplier": "GamerZone - SP",
    "description": "Crie atmosferas imersivas com sincronização musical e 16 milhões de cores via app."
  },
  {
    "id": "68",
    "name": "Headset Gamer Surround 7.1 Som Espacial com Microfone Noise Cancelling",
    "title": "Headset Gamer Surround 7.1 Som Espacial com Microfone Noise Cancelling",
    "price": 149.9,
    "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 48,00",
    "vendas_mes": 3120,
    "supplier": "CyberDesk - SP",
    "description": "Almofadas confortáveis que não esquentam e áudio posicional para ouvir passos dos inimigos."
  },
  {
    "id": "69",
    "name": "Apoio de Pulso Ergonômico em Gel para Teclado e Mouse",
    "title": "Apoio de Pulso Ergonômico em Gel para Teclado e Mouse",
    "price": 54.9,
    "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&q=80&w=800",
    "hype_score": 92,
    "score": 92,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Setup Gamer",
    "commission": "R$ 17,50",
    "vendas_mes": 2450,
    "supplier": "ErgoDesign - SC",
    "description": "Alívio instantâneo para tendinites e cansaço nos pulsos durante longas jornadas de trabalho."
  },
  {
    "id": "70",
    "name": "Corda de Pular de Aço com Rolamento Profissional Speed Rope",
    "title": "Corda de Pular de Aço com Rolamento Profissional Speed Rope",
    "price": 39.9,
    "image_url": "https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&q=80&w=800",
    "hype_score": 97,
    "score": 97,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 12,70",
    "vendas_mes": 4620,
    "supplier": "FitLife Brasil - SP",
    "description": "Giro suave ultrarrápido com rolamento duplo blindado, ideal para Crossfit e queima calórica."
  },
  {
    "id": "71",
    "name": "Hand Grip com Contador Ajustável de Força 10kg a 60kg",
    "title": "Hand Grip com Contador Ajustável de Força 10kg a 60kg",
    "price": 34.9,
    "image_url": "https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 11,10",
    "vendas_mes": 4180,
    "supplier": "FitLife Brasil - SP",
    "description": "Fortalecimento de antebraço, dedos e pegada com contador mecânico de repetições."
  },
  {
    "id": "72",
    "name": "Smart Band Pulseira Inteligente M8 Monitor Cardíaco Fitness",
    "title": "Smart Band Pulseira Inteligente M8 Monitor Cardíaco Fitness",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 22,30",
    "vendas_mes": 3950,
    "supplier": "TechMaster Brasil - SP",
    "description": "Passos, calorias, batimentos e notificações direto no seu pulso com bateria de 14 dias."
  },
  {
    "id": "73",
    "name": "Kit 3 Faixas Elásticas de Tecido Hip Resistance Bands para Pernas",
    "title": "Kit 3 Faixas Elásticas de Tecido Hip Resistance Bands para Pernas",
    "price": 59.9,
    "image_url": "https://images.unsplash.com/photo-1598289431512-b97b0917affc?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Fitness",
    "commission": "R$ 19,00",
    "vendas_mes": 2890,
    "supplier": "FitLife Brasil - SP",
    "description": "Tecido premium antiderrapante que não enrola na perna nem machuca a pele."
  },
  {
    "id": "74",
    "name": "Suporte Veicular Celular com Trava por Gravidade para Saída de Ar",
    "title": "Suporte Veicular Celular com Trava por Gravidade para Saída de Ar",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 16,00",
    "vendas_mes": 4320,
    "supplier": "AutoTech Express - SP",
    "description": "Encaixe automático por peso: basta soltar o celular que o suporte fecha sozinho."
  },
  {
    "id": "75",
    "name": "Aromatizador Automotivo Giratório Solar Helicóptero Metal Luxo",
    "title": "Aromatizador Automotivo Giratório Solar Helicóptero Metal Luxo",
    "price": 59.9,
    "image_url": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800",
    "hype_score": 95,
    "score": 95,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 19,00",
    "vendas_mes": 3890,
    "supplier": "AutoTech Express - SP",
    "description": "Hélice gira automaticamente sob luz solar espalhando perfume agradável pelo interior do veículo."
  },
  {
    "id": "76",
    "name": "Kit Iluminação LED Automotiva RGB para Assoalho com Sensor Musical",
    "title": "Kit Iluminação LED Automotiva RGB para Assoalho com Sensor Musical",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 22,30",
    "vendas_mes": 3210,
    "supplier": "AutoTech Express - SP",
    "description": "Transforme o interior do seu carro em uma balada com luzes sincronizadas com o som automotivo."
  },
  {
    "id": "77",
    "name": "Câmera Veicular Dash Cam HD 1080P Visão Noturna e Gravação em Loop",
    "title": "Câmera Veicular Dash Cam HD 1080P Visão Noturna e Gravação em Loop",
    "price": 139.9,
    "image_url": "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&q=80&w=800",
    "hype_score": 93,
    "score": 93,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Automotivo",
    "commission": "R$ 44,70",
    "vendas_mes": 2750,
    "supplier": "AutoSegura - SP",
    "description": "Segurança contra acidentes e fraudes com gravação contínua automática no para-brisa."
  },
  {
    "id": "78",
    "name": "Mochila Antifurto Executiva Impermeável com Trava TSA e Saída USB",
    "title": "Mochila Antifurto Executiva Impermeável com Trava TSA e Saída USB",
    "price": 159.9,
    "image_url": "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&q=80&w=800",
    "hype_score": 98,
    "score": 98,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 51,00",
    "vendas_mes": 4890,
    "supplier": "Bolsas & Cia - SP",
    "description": "Zíperes ocultos, trava por código e material à prova de cortes para transporte de laptops e documentos."
  },
  {
    "id": "79",
    "name": "Carteira Slim Masculina de Fibra de Carbono com Trava RFID",
    "title": "Carteira Slim Masculina de Fibra de Carbono com Trava RFID",
    "price": 49.9,
    "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=800",
    "hype_score": 96,
    "score": 96,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 16,00",
    "vendas_mes": 3950,
    "supplier": "CouroFino - RS",
    "description": "Apenas 8mm de espessura com ejeção rápida de cartões e proteção contra clonagem por aproximação."
  },
  {
    "id": "80",
    "name": "Óculos de Sol Retrô Polarizado Masculino e Feminino Proteção UV400",
    "title": "Óculos de Sol Retrô Polarizado Masculino e Feminino Proteção UV400",
    "price": 69.9,
    "image_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=800",
    "hype_score": 94,
    "score": 94,
    "url": "https://shopee.com.br",
    "status": "ALTA",
    "category": "Moda",
    "commission": "R$ 22,30",
    "vendas_mes": 3120,
    "supplier": "GlamourBR - SP",
    "description": "Lentes polarizadas de alta definição que eliminam reflexos solares com armação vintage estilosa."
  }
];

export const tips = [
  "Produtos com Hype Score > 90 convertem 3.4x mais nos primeiros 7 dias de anúncio.",
  "Anúncios gerados no TikTok Shop têm maior conversão com ganchos de curiosidade de 3 segundos.",
  "Produtos com despacho nacional de 24 horas reduzem cancelamentos em 88%."
];
