-- =======================================================
-- DECOLASHOP SAAS - SCHEMA & DADOS INICIAIS DO SUPABASE
-- Execute este script no SQL Editor do seu novo Supabase
-- =======================================================

-- 1. Criação da tabela Product
CREATE TABLE IF NOT EXISTS public."Product" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    price NUMERIC(10, 2) NOT NULL DEFAULT 99.90,
    url TEXT,
    image_url TEXT,
    hype_score NUMERIC(4, 2) DEFAULT 8.5,
    description TEXT
);

-- 2. Habilitar Row Level Security (RLS)
ALTER TABLE public."Product" ENABLE ROW LEVEL SECURITY;

-- 3. Permitir leitura pública (para que seu frontend e clientes acessem os produtos)
DROP POLICY IF EXISTS "Permitir leitura publica de produtos" ON public."Product";
CREATE POLICY "Permitir leitura publica de produtos"
    ON public."Product"
    FOR SELECT
    USING (true);

-- 4. Permitir inserção e atualização autenticada ou via chave de serviço
DROP POLICY IF EXISTS "Permitir gerenciar produtos autenticado" ON public."Product";
CREATE POLICY "Permitir gerenciar produtos autenticado"
    ON public."Product"
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- 5. Inserção dos 15 Produtos Reais Vencedores do Mercado
INSERT INTO public."Product" ("ID", name, price, url, image_url, hype_score, description) VALUES
(58, 'Microfone Condensador Profissional e Gadgets Tech', 197.90, 'https://www.tiktok.com/@renaninez/video/7351441616185347334', 'https://loja.ctmd.eng.br/34608-large/microfone-condensador-profissional-cardioide-shure-138db.jpg', 9.5, 'Eleve o nível da sua produção de conteúdo com este microfone de alta fidelidade sonora, perfeito para streamers e podcasters que buscam clareza absoluta.'),
(59, 'Sandália Crocs Feminina Soft Comfort', 189.90, 'https://www.tiktok.com/discover/sandale-crocs-femme', 'https://cdn.dooca.store/1290/products/crocband-white-pink-caramel-2_640x640+fill_ffffff.jpg?v=1755529361&webp=0', 9.5, 'A combinação perfeita de estilo moderno e conforto absoluto, ideal para quem busca leveza e praticidade sem abrir mão de um design premium para o dia a dia.'),
(65, 'Bolsa Transversal Joey de Luxo', 189.90, 'https://www.tiktok.com/@kamyjayy/video/7628935056374926600', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1779628861/nwueymcgocc18bhfftl8.webp', 9.8, 'Eleve seu estilo com a bolsa transversal que é fenômeno de vendas; design sofisticado e acabamento premium que garantem praticidade e elegância em qualquer ocasião.'),
(67, 'Batedor de Ovos e Bebidas Portátil Sem Fio', 89.90, 'https://www.tiktok.com/@sarahwithanh00/video/7475854970261196063', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1779631797/sipvxlzvr2llsrid2qmc.jpg', 9.5, 'Praticidade absoluta na palma da sua mão. Misture bebidas, bata ovos e prepare receitas em segundos sem fios e sem esforço na sua cozinha.'),
(70, 'Dispenser Automático de Pasta de Dente Higiênico', 79.90, 'https://www.tiktok.com/@mjeuqnar/video/7241533259090300166', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1779676433/t9y5gf21oqbr2j0ipglf.jpg', 8.5, 'Transforme sua rotina matinal com tecnologia de vácuo que libera a quantidade perfeita de pasta sem sujeira e sem desperdício no seu banheiro.'),
(74, 'Aspirador de Pó Sem Fio Airbot Swift', 749.90, 'https://www.tiktok.com/@xiaowang626/video/7528398756941745415', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1780001839/qzonzlcs6eob01alv9to.webp', 8.5, 'Diga adeus aos fios e ao peso! Este aspirador ultra-potente e leve transforma a limpeza da sua casa em uma experiência rápida, prática e sem esforço.'),
(76, 'Calça Jogger Minimalista Soft Comfort', 189.90, 'https://www.tiktok.com/@reeserrelly/video/7588273607944572191', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1780241187/umwqblqntggmalzuby3u.jpg', 9.5, 'Experimente o ápice do conforto com esta peça de design clean que une estilo urbano e toque aveludado, perfeita para quem não abre mão do bem-estar.'),
(55, 'Suporte de Celular PopSocket Estético Studio Ghibli', 49.90, 'https://www.tiktok.com/@strawburrislushie/video/7235967814228593922', 'https://m.media-amazon.com/images/I/91QcppY+juL.jpg', 9.5, 'Personalize seu smartphone com o charme irresistível das animações clássicas. Este suporte oferece segurança ergonômica para evitar quedas e um design exclusivo que transforma seu aparelho em uma peça de coleção.'),
(57, 'Sandália Feminina Plataforma Chunky', 189.90, 'https://www.tiktok.com/@queenilain22/video/7600676955515538708', 'https://img.joomcdn.net/e3d6508594d03c7b7a21b98aa453b581e14abcb3_original.jpeg', 9.5, 'Eleve seu estilo e sua altura com o máximo conforto; a sandália tratorada que é tendência absoluta e combina com qualquer look de verão.'),
(71, 'Intercomunicador V2 Bluetooth para Capacete', 289.90, 'https://www.tiktok.com/@blaiseintercom_ph/video/7632671220265127189', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1779676505/jsfylaae9w4lcbftcewj.jpg', 9.2, 'Eleve sua experiência sobre duas rodas com o Intercomunicador V2. Comunique-se com clareza cristalina, atenda chamadas e ouça suas playlists favoritas com total segurança e sem fios durante suas viagens.'),
(24, 'Cortador de Legumes Multifuncional 12 em 1', 87.90, 'https://www.youtube.com/watch?v=O6UJd1K_uqo', 'https://m.media-amazon.com/images/I/61Ec2TdhRWL._AC_UF1000,1000_QL80_.jpg', 9.5, 'Prepare suas refeições com a agilidade de um chef profissional! Este fatiador versátil oferece múltiplas funções em um único aparelho, permitindo fatiar, ralar e cortar legumes em segundos com total segurança e precisão.'),
(73, 'Organizador de Canto em Bambu para Banheiro', 189.90, 'https://www.tiktok.com/@pep_home/video/7330994521523719430', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1779761533/m5fdmmwgaptszvqpd9r8.jpg', 8.5, 'Eleve o nível do seu banheiro com este organizador premium em bambu natural. Design sustentável e sofisticado que maximiza o espaço com elegância e resistência à umidade.'),
(75, 'Bandeira do Brasil Copa do Mundo 2026 150x105cm', 39.90, 'https://shopee.com.br/Bandeira-do-Brasil-Copa-do-Mundo-2026-150x105cm-i.101234.56789', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1780320783/bandeira_brasil_2026_yhdamv.jpg', 9.8, 'Prepare-se para o Hexa com a bandeira oficial do Brasil para a Copa do Mundo de 2026. Sendo um dos maiores virais e tendências de venda da Shopee, este produto oferece alta margem de lucro e forte apelo emocional. Fabricada em poliéster premium leve e resistente, com cores vivas e costura dupla reforçada de alta qualidade.'),
(79, 'Boneco Colecionável Sonny Angel Série Sweet', 127.90, 'https://www.tiktok.com/@any.pomy.pomy/video/7293588361292336416', 'https://res.cloudinary.com/dwtefghdi/image/upload/v1780783993/k7mjdmcebbcxfjzepomd.webp', 9.8, 'A maior febre colecionável do momento chegou! Garanta a experiência mágica do unboxing e adicione um toque de fofura irresistível à sua decoração com os autênticos Sonny Angels.'),
(31, 'Cortador de Vegetais Multifuncional', 89.00, 'https://www.tiktok.com/@saucceats/video/7589754556549057813', 'https://m.media-amazon.com/images/I/61Hp7MWMuzL.jpg', 9.5, 'O utensílio de cozinha mais viral de 2024, permitindo picar, fatiar e ralar legumes em segundos com segurança e precisão.')
ON CONFLICT ("ID") DO UPDATE 
SET 
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    url = EXCLUDED.url,
    image_url = EXCLUDED.image_url,
    hype_score = EXCLUDED.hype_score,
    description = EXCLUDED.description;
